app = 'sarzal'
primary_region = 'ams'

[build]

# Pas de [http_service] = mode worker pur (pas de port exposé)
# Le moniteur CESAL tourne en boucle infinie via src/loop.js

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
