# fly.toml app configuration file generated for sarzal-crfugg on 2026-08-01T21:59:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sarzal-crfugg'
primary_region = 'ams'

[build]

[processes]
  app = 'sh start.sh'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1024mb'
